from app.utils.provenance import build_provenance


def test_file_tag_field_reclassified_to_extracted():
    """title is AI_GENERATED by default, but EXTRACTED when the file's own
    tag actually won during the merge in routes/analysis.py."""
    metadata = {"title": "My Song", "bpm": 120}
    provenance = build_provenance(metadata, file_tag_fields={"title"}, overall_confidence=0.8)

    assert provenance["title"]["source"] == "EXTRACTED"
    assert provenance["title"]["confidence"] == 1.0
    assert provenance["title"]["method"] == "technical-parser"


def test_ai_field_without_file_tag_stays_ai_generated():
    metadata = {"title": "My Song"}
    provenance = build_provenance(metadata, file_tag_fields=set(), overall_confidence=0.8)

    assert provenance["title"]["source"] == "AI_GENERATED"
    assert provenance["title"]["confidence"] == 0.8


def test_dsp_field_is_inferred():
    metadata = {"bpm": 128.0}
    provenance = build_provenance(metadata, file_tag_fields=set(), overall_confidence=0.9)

    # DSP-derived fields use their own default confidence, not the overall
    # AI ensemble confidence — they don't come from the LLM ensemble at all.
    assert provenance["bpm"]["source"] == "INFERRED"
    assert provenance["bpm"]["method"] == "dsp-analysis"
    assert provenance["bpm"]["confidence"] == 0.7


def test_missing_field_is_unknown():
    metadata = {}
    provenance = build_provenance(metadata, file_tag_fields=set(), overall_confidence=0.9)

    assert provenance["mood_vibe"]["source"] == "UNKNOWN"
    assert provenance["mood_vibe"]["confidence"] == 0.0


def test_empty_string_and_empty_list_count_as_missing():
    metadata = {"trackDescription": "", "moods": [], "musicalEra": None}
    provenance = build_provenance(metadata, file_tag_fields=set(), overall_confidence=0.9)

    assert provenance["trackDescription"]["source"] == "UNKNOWN"
    assert provenance["moods"]["source"] == "UNKNOWN"
    assert provenance["musicalEra"]["source"] == "UNKNOWN"


def test_technical_fact_fields_are_extracted_with_full_confidence():
    metadata = {"duration": 185.3, "sha256": "abc123"}
    provenance = build_provenance(metadata, file_tag_fields=set(), overall_confidence=0.5)

    assert provenance["duration"]["source"] == "EXTRACTED"
    assert provenance["duration"]["confidence"] == 1.0
    assert provenance["sha256"]["source"] == "EXTRACTED"


def test_no_overall_confidence_falls_back_to_default():
    metadata = {"mainGenre": "House"}
    provenance = build_provenance(metadata, file_tag_fields=set(), overall_confidence=None)

    assert provenance["mainGenre"]["source"] == "AI_GENERATED"
    assert provenance["mainGenre"]["confidence"] == 0.6  # documented AI_GENERATED default


def test_every_allowed_field_gets_a_provenance_entry():
    """Sanity check that the classification table stays in sync with
    itself — every field it knows about produces a well-formed entry."""
    from app.utils.provenance import DEFAULT_FIELD_SOURCE

    provenance = build_provenance({}, file_tag_fields=set(), overall_confidence=0.5)
    assert set(provenance.keys()) == set(DEFAULT_FIELD_SOURCE.keys())
    for field, entry in provenance.items():
        assert entry["source"] in ("VERIFIED", "EXTRACTED", "INFERRED", "AI_GENERATED", "UNKNOWN")
        assert 0.0 <= entry["confidence"] <= 1.0
        assert entry["method"]
